### ISSUE TITLE
BaseException: Failed retrieving open-meteo data, server returned HTTP code: 414 on following URL ..

### ISSUE THREAD

**Issue by jimoreira** [m0rp43us/openmeteopy#3]
congratulations for your work, really helping over here.

when using these in a for loop it fails with error 414 when the loop runs 34 times. 
the URL presented in the error shows a repetition of the variables requested in the URL provided. Perhaps 34, couldn't count them right.

so i wonder why OWmanager() that is using a different set of Options() is producing a url with repeted variables? 

many thanks if you can provide some insights

br

**Comment by jimoreira** [comment]
Sorry. Solved. 
I was running daily = Daily() outside of the loop and then calling daily.all() inside of the loop. 
thanks!

**Comment by m0rp43us** [comment]
Appologies just found the open issue,glad you found the bug.
good luck with the rest !
