### ISSUE TITLE
Add support for commercial use

### ISSUE THREAD

**Issue by Tatallias** [m0rp43us/openmeteopy#5]
The customer API service is tailored for commercial use and offers dedicated API server instances to ensure enough resources are available and the API operates reliably. The customer API is using different domains like customer-api.open-meteo.com and API keys in the URL &apikey=abc123. Otherwise the syntax is exactly the same.

see [Pricing](https://open-meteo.com/en/pricing)

**Comment by m0rp43us** [comment]
Hello @Tatallias ,

I'll work on that the next days
