### ISSUE TITLE
historical data

### ISSUE THREAD

**Issue by iammehdii** [m0rp43us/openmeteopy#7]
Hi. I am very thankful for this great work. I have a question is this repository only works for forecasting?
I could not find how it is works for historical data
thanks in advance
mehdi

**Comment by m0rp43us** [comment]
I'll add that feature in the next couple of days

**Comment by Sarthak-Singh1996** [comment]
Is this issue resolved ?

**Comment by m0rp43us** [comment]
Second version of the librairy will be published soon,appologies for the delay

**Comment by m0rp43us** [comment]
issue resolved
